[tools]
bat = "latest"
bottom = "latest"
bun = "latest"
chezmoi = "latest"
delta = "latest"
deno = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
gcloud = "latest"
git-lfs = "latest"
github-cli = "latest"
jaq = "latest"
neovim = "latest"
node = "latest"
pixi = "latest"
rclone = "latest"
ripgrep = "latest"
rust = "latest"
sops = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
vault = "latest"
zoxide = "latest"
